services:
    serve:
        build: .
        env_file:
            - .env
        command: ["serve"]
        volumes:
            - ./music:/music:ro
        depends_on:
            - db
        ports:
            - 8001:80

    db:
        image: pgvector/pgvector:pg16
        env_file:
            - .env
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
